spawns:
  farming:
    1:
      x: 0.5
      y: 120
      z: 800.5
    2:
      x: 400.5
      y: 120
      z: 800.5
    3:
      x: -400.5
      y: 120
      z: 800.5
    4:
      x: 800.5
      y: 120
      z: 800.5
    5:
      x: -800.5
      y: 120
      z: 800.5
    6:
      x: 0.5
      y: 120
      z: -800.5
    7:
      x: 400.5
      y: 120
      z: -800.5
    8:
      x: -400.5
      y: 120
      z: -800.5
    9:
      x: 800.5
      y: 120
      z: -800.5
    10:
      x: -800.5
      y: 120
      z: -800.5
    11:
      x: 800.5
      y: 120
      z: 0.5
    12:
      x: 800.5
      y: 120
      z: 400.5
    13:
      x: 800.5
      y: 120
      z: 800.5
    14:
      x: -800.5
      y: 120
      z: 0.
    15:
      x: -800.5
      y: 120
      z: 400.5
    16:
      x: -800.5
      y: 120
      z: 800.5
  fight:
    1:
      x: 0.5
      y: 120
      z: 180.5
    2:
      x: 90.5
      y: 120
      z: 180.5
    3:
      x: -90.5
      y: 120
      z: 180.5
    4:
      x: 18.5
      y: 120
      z: 180.5
    5:
      x: -180.5
      y: 120
      z: 180.5
    6:
      x: 0.5
      y: 120
      z: -180.5
    7:
      x: 90.5
      y: 120
      z: -180.5
    8:
      x: -90.5
      y: 120
      z: -180.5
    9:
      x: 180.5
      y: 120
      z: -180.5
    10:
      x: -180.5
      y: 120
      z: -180.5
    11:
      x: 180.5
      y: 120
      z: 0.5
    12:
      x: 180.5
      y: 120
      z: 90.5
    13:
      x: 180.5
      y: 120
      z: 180.5
    14:
      x: -180.5
      y: 120
      z: 0.
    15:
      x: -180.5
      y: 120
      z: 90.5
    16:
      x: -180.5
      y: 120
      z: 180.5